load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("@rules_oci//oci:defs.bzl", "oci_push")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_doc", "rust_doc_test")
load("//:build/binary.bzl", "build_binary_opt")
load("//:build/container.bzl", "build_multi_arch_image", "git_with_timestamp_tag")

filegroup(
    name = "all",
    srcs = [
        ":hello_world_host",
        ":hello_linux_x86_64_musl",
        ":hello_linux_arm64_musl",
    ],
)

rust_binary(
    name = "hello_world_host",
    srcs = ["src/main.rs"],
    deps = [
        # External crates
        "//thirdparty/crates:mimalloc",
        "//thirdparty/crates:lz4-sys",
        "//thirdparty/crates:diesel",
        "//thirdparty/crates:tokio",
    ],
)

# Test if the host binary works.
# Note, we cannot test for platform since Bazel determines the host platform automatically
sh_test(
    name = "test_hello_world_host",
    srcs = ["test_hello_world.sh"],
    args = [
        "$(rlocationpath :hello_world_host)",
    ],
    data = [
        ":hello_world_host",
    ],
    deps = [
        "@bazel_tools//tools/bash/runfiles",
    ],
)

rust_binary(
    name = "hello_linux_x86_64_musl",
    srcs = ["src/main.rs"],
    platform = "//build/platforms:linux_x86_64_musl",
    deps = [
        # External crates
        "//thirdparty/crates:mimalloc",
        "//thirdparty/crates:lz4-sys",
        "//thirdparty/crates:diesel",
        "//thirdparty/crates:tokio",
    ],
)

# Test the for x86_64 architecture
sh_test(
    name = "test_hello_linux_x86_64_musl",
    srcs = ["test_platform.sh"],
    args = [
        "$(rootpath :hello_linux_x86_64_musl)",
       "'ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked'",
    ],
    data = [
        ":hello_linux_x86_64_musl",
    ],
    deps = [
        "@bazel_tools//tools/bash/runfiles",
    ],
)

rust_binary(
    name = "hello_linux_arm64_musl",
    srcs = ["src/main.rs"],
    platform = "//build/platforms:linux_arm64_musl",
    deps = [
        # External crates
        "//thirdparty/crates:mimalloc",
        "//thirdparty/crates:lz4-sys",
        "//thirdparty/crates:diesel",
        "//thirdparty/crates:tokio",
    ],
)


# Test for ARM architecture
sh_test(
    name = "test_hello_linux_arm64_musl",
    srcs = ["test_platform.sh"],
    args = [
        "$(rootpath :hello_linux_arm64_musl)",
       "'ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked'",
    ],
    data = [
        ":hello_linux_arm64_musl",
    ],
    deps = [
        "@bazel_tools//tools/bash/runfiles",
    ],
)


###############################################################################
# RUST RELEASE MODE OPTIMIZATION
###############################################################################
config_setting(
    name = "release",
    values = {
        "compilation_mode": "opt",
    },
)

###############################################################################
# Rust Binary compiler optimized for production
###############################################################################
build_binary_opt(
    name = "hello_world_bin",
    srcs = ["src/main.rs"],
    deps = [
        # External crates
        "//thirdparty/crates:mimalloc",
        "//thirdparty/crates:lz4-sys",
        "//thirdparty/crates:diesel",
        "//thirdparty/crates:tokio",
    ],
)


###############################################################################
# Documentation
###############################################################################
rust_doc(
    name = "doc",
    crate = ":hello_world_bin",
    tags = ["doc"],
    visibility = ["//visibility:public"],
)

rust_doc_test(
    name = "doc_test",
    crate = ":hello_world_bin",
    tags = ["doc-test"],
    visibility = ["//visibility:public"],
)

###############################################################################
# OCI Container Image
###############################################################################
build_multi_arch_image(
    name = "image_index",
    srcs = ["hello_world_bin"],
    base = "@scratch",
    entry_point = "hello_world_bin",
    exposed_ports = [
        "7070",
    ],
    platforms = [
       "//build/platforms:linux_x86_64_musl",
       "//build/platforms:linux_arm64_musl",
    ],
    visibility = ["//visibility:public"],
)

git_with_timestamp_tag(
    name = "remote_tag",
    target = ":image_index",
)

oci_push(
    name = "push",
    image = ":image_index",
    remote_tags = ":remote_tag",
    repository = "my_registry/my_project/my_repo/my_image",
    visibility = ["//visibility:public"],
)
